### ISSUE TITLE
Version should match eslint?

### ISSUE THREAD

**Issue by goldingdamien** [origin-1/gulp-eslint-new#7]
Just a small concern of mine.
Should libraries like this that are highly dependent on another library(eslint), use similar versioning?
It seems this is often the case, but I haven't really researched it to see just how standard this is.
My last version of gulp-eslint is 6 which I assume at least matches the major version of eslint.

**Comment by fasttime** [comment]
Hi @goldingdamien! I'm not sure about this suggestion because
1. gulp-eslint-new depends equally on ESLint and gulp.
1. There are a few well-know libs that don't follow this versioning schema: gulp-sass, gulp-terser, etc.
1. The limitation to one particular major version of ESLint could be dropped in the future (for example, we may want to support both ESLint 8 and 9).

**Comment by goldingdamien** [comment]
@fasttime Ok, thanks for justification.
